CircleCI-Public/android-orb

- .circleci/config.yml
- src/executors/android.yml
The latest Android SDK version is 29. This PR should add that version to the Android Orb.
- Add SDK version 29 to the sdk-version enum
- Set default version to 29
> feat: add sdk-version 29 and make it the default

- src/commands/install-ndk.yml
resolves https://github.com/CircleCI-Public/android-orb/issues/7
curl is having HTTP2 framing layer error, most likely due to
https://github.com/curl/curl/issues/3750 and
https://github.com/curl/curl/issues/4267.
Since it is having an error when using HTTP2, we should force HTTP1.1
when downloading.
Another option is to use `wget`, but `wget` is not usually installed by
default in Linux distributions.
- force http1.1 in curl command
> [semver:patch] Force HTTP1.1 when downloading via curl

- .circleci/config.yml
- .github/CODEOWNERS
- LICENSE
- README.md
- src/@orb.yml
- src/commands/accept-licenses.yml
- src/commands/create-avd.yml
- src/commands/disable-animations.yml
- src/commands/install-ndk.yml
- src/commands/kill-emulators.yml
- src/commands/restore-build-cache.yml
- src/commands/restore-gradle-cache.yml
- src/commands/run-tests.yml
- src/commands/save-build-cache.yml
- src/commands/save-gradle-cache.yml
- src/commands/start-emulator-and-run-tests.yml
- src/commands/start-emulator.yml
- src/commands/wait-for-emulator.yml
- src/examples/override-machine-resource-class.yml
- src/examples/run-ui-tests-job.yml
- src/examples/start-emulator-and-run-tests.yml
- src/examples/test-matrix.yml
- src/examples/ui-tests.yml
- src/executors/android-machine.yml
- src/jobs/run-ui-tests.yml
The new [Android machine image](https://github.com/CircleCI-Public/android-image-preview-docs) (currently in preview status) has support for running emulators. This PR adds new commands and a job to support running UI tests.
**Additions**
- New commands:
- `create-avd` for creating an AVD
- `disable-animations` to disable emulator animations
- `kill-emulators` command to kill emulator processes
- `restore-gradle-cache` and `save-gradle-cache`
- `run-tests` to run tests, with retries supported
- `start-emulator` to start an emulator from an existing AVD
- `wait-for-emulator` to wait for an emulator to start up
- `start-emulator-and-run-tests`: a command that wraps `create-avd`, `start-emulator` and `run-tests`
- New job: `run-ui-tests` that wraps the `start-emulator-and-run-tests` command …
> [semver:major] Add commands and job for working with the Android emulator

- src/examples/granular-commands.yml
- src/examples/run-ui-tests-job.yml
- src/examples/start-emulator-and-run-tests.yml
- Add more annotations to orb examples
- Add example of using more granular commands
> [semver: patch] Add more annotations to orb examples

- src/commands/restore-build-cache.yml
- src/commands/restore-gradle-cache.yml
- src/commands/save-build-cache.yml
- src/commands/save-gradle-cache.yml
Improve naming of the cache commands as displayed in the builds, so that the restore/save gradle/build cache commands are more distinguishable from each other
> [semver:patch] Improve naming of cache commands

- .circleci/config.yml
- src/commands/start-emulator-and-run-tests.yml
- src/commands/start-emulator.yml
- src/jobs/run-ui-tests.yml
- Change default value of `-delay-adb` to false as when set to true, it can cause the emulator to not finish starting up, for system images with older API levels (typically <26). See example of failed job: https://app.circleci.com/pipelines/github/CircleCI-Public/android-orb/107/workflows/0c44a7a3-a223-492d-be02-dc9ce5181375/jobs/1731
- Rearrange parameter listing of `run-ui-tests` job for easier referencing of most-used parameters
> [semver:patch] Default delay-adb to false to improve support for older API levels

- src/executors/android.yml
- src/jobs/build.yml
As same as Android Machine executor, I added `resource-class` parameter for Docker Executor
> [semver:minor] Add parameter resource-class for android docker executor

- .circleci/config.yml
- .circleci/test-deploy.yml
- .yamllint
- publish-alpha.sh
The orb's deployment process was outdated and [non-functional](https://app.circleci.com/pipelines/github/CircleCI-Public/android-orb/180/workflows/45110c9c-cd88-4087-ba0c-c1fc39a664bf/jobs/2361).
No functional changes were made.
> ci: migrate to Orb Tools 11

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/commands/change-java-version.yml
Added a new job to allow switch OpenJDK versions per [this issue](https://github.com/CircleCI-Public/android-orb/issues/31)
Description
Wrote a command with 3 steps, the first to check the current OpenJDK version, the second changes the default OpenJDK version of the current image to OpenJDK v8, and the third step confirms the change by running java -version once more
Also, added a parameter that will allow you to change OpenJDK versions, default: '1.8.0'. To check available OpenJDK versions, run `update-java-alternatives --list`
> Add command to change OpenJDK versions from 11 to 8

- .circleci/test-deploy.yml
- src/commands/install-ndk.yml
This fix was drafted in response to the following issue: https://github.com/CircleCI-Public/android-orb/issues/39
Added conditional to install-ndk command so ANDROID_NDK_HOME will be set either with `$HOME/android-sdk/ndk/<< parameters.version >> ` or `/opt/android/sdk/ndk/<< parameters.version >>` with the default being the former
> fix: Added handling for different paths for ANDROID_NDK_HOME

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/commands/change-java-version.yml
- src/commands/create-avd.yml
- src/commands/disable-animations.yml
- src/commands/install-ndk.yml
- src/commands/kill-emulators.yml
- src/commands/restore-gradle-cache.yml
- src/commands/run-tests.yml
- src/commands/start-emulator.yml
- src/scripts/change-java-version.sh
- src/scripts/create-avd.sh
- src/scripts/disable-animations.sh
- src/scripts/generate-cache-checksum.sh
- src/scripts/install-ndk.sh
- src/scripts/kill-emulators.sh
- src/scripts/run-tests.sh
- src/scripts/start-emulator.sh
This pull request should close [issue #37](https://github.com/CircleCI-Public/android-orb/issues/37)
Refactored the commands that were longer than 64 characters into their own .sh files in a separate scripts directory found under ./src/scripts
> refactor: Refactored code to pass RC009 check

- src/commands/restore-gradle-cache.yml
This pull request should resolve (issue #21 )[https://github.com/CircleCI-Public/android-orb/issues/21].
> perf: added kts files to cache key

- src/commands/restore-gradle-cache.yml
- src/commands/start-emulator-and-run-tests.yml
- src/commands/start-emulator.yml
- src/jobs/run-ui-tests.yml
- src/scripts/generate-cache-checksum.sh
Added eval to the find command for `generate-cache-checksum` and reworded the default parameter for `PARAM_FIND_ARGS` to be easier to read. This should close [issue #49](https://github.com/CircleCI-Public/android-orb/issues/49)
> fix: added eval to find command

- .circleci/config.yml
- .circleci/test-deploy.yml
- src/executors/android-machine.yml
The tag is required, and it was unclear where to find it.
Updated machine executor tag parameter description with dev hub link.
Also removed the reference to preview status archived repository
> docs: Include link to Android machine tags list

- .circleci/test-deploy.yml
- src/commands/create-avd.yml
- src/scripts/create-avd.sh
Added the ability to run create-avd in background, moved all run steps of `create-avd.yml `into the `create-avd.sh` file, and fixed the test-fastlane step of the `test-deploy` config. This should close [#63 ](https://github.com/CircleCI-Public/android-orb/issues/63)
> feat: added background to create-avd

- .circleci/test-deploy.yml
- src/commands/run-tests.yml
- src/commands/start-emulator-and-run-tests.yml
- src/jobs/run-ui-tests.yml
- src/scripts/run-tests.sh
This PR should close [#57](https://github.com/CircleCI-Public/android-orb/issues/57) by adding a parameter to `run-tests` that allows users to run a command before their test command
> feat: add pre test command

- .circleci/test-deploy.yml
- src/commands/run-tests.yml
- src/commands/start-emulator-and-run-tests.yml
- src/jobs/run-ui-tests.yml
this should close #55 , adds a parameter to the `run-ui-tests` job, `start-emulator-and-run-tests` command and the `run-tests` command for running `adb pull` after your test run.
> feat: add adp pull parameter

- src/commands/run-tests.yml
The "no-output-timeout" parameter should actually be passed on to the test command
> Actually pass the no output timeout to run-tests

- .circleci/test-deploy.yml
- src/commands/change-java-version.yml
- src/scripts/change-java-version.sh
This PR does the following changes:
* Upgrades the test image for the `test-java-version` to the new `android:2023.03.1` docker image
* Widens the net for testing this command, now tests for 8, 11, 17 and 18 to test for both installed versions, one older than the current, and one newer
* Improves the name for the `change_java_version` command
* Fixes an issue with installing an older version of java than the current
> fix: change java version command to handle java 17 being installed instead of 11

- src/commands/create-google-play-key.yml
This should close #75 and allow for the `deploy-to-play-store` job to be used as intended
> fix: passed env var correctly to create play key

- src/scripts/change-java-version.sh
The Java 11 test had been failing for `change-java-version` so I went in and added sudo apt-get update before the install to alleviate this issue.
> fix: fix java installs

- .circleci/test-deploy.yml
- src/examples/granular-commands.yml
- src/examples/override-machine-resource-class.yml
- src/examples/run-ui-tests-job.yml
- src/examples/start-emulator-and-run-tests.yml
- src/examples/test-matrix.yml
- Per [Android Image Deprecations and EOL for 2024](https://discuss.circleci.com/t/android-image-deprecations-and-eol-for-2024/50180) the recommended tags (for android/machine) are default and edge.  This PR addresses these.
- Orb version refs were updated to reflect the current/latest android orb version in examples.
- Replace android/machine tags to `default`
- Update android/orb version to "2.4.0"
> fix: Use recommended machine tags

- .github/CODEOWNERS
Updates the CODEOWNERS file to use the orb-publishers team like the rest of our orbs.
> Update CODEOWNERS to use orb-publishers team

- .circleci/test-deploy.yml
- src/@orb.yml
- src/commands/create_avd.yml
- src/commands/run_tests.yml
- src/commands/start_emulator.yml
- src/commands/start_emulator_and_run_tests.yml
- src/examples/test_matrix.yml
- src/jobs/deploy_to_play_store.yml
- src/scripts/create_avd.sh
- src/scripts/install_ndk.sh
- src/scripts/run_tests.sh
I'm updating the context to use in the publish step to avoid issues with the old context used.
I'm also adding the possibility to pass some of the parameters as environment variables, this was possible in version 2.1.0 and previous, based on issue #56.
I'm also fixing the android_ndk_home path, based on issue #91.
> Update context to use in publish

- .circleci/test-deploy.yml
- src/executors/android_machine.yml
- src/scripts/create_avd.sh
- src/scripts/run_tests.sh
Resolves #104 
The parameter PARAM_ADDITIONAL_ARGS is having an issue when replaced inside script, as the flags can be considered part of the circleci command instead of the full parameter. I'm updating the way the value is passed to avoid this problem.
A new test is added to validate this behavior.
> Fix issue when replacing arguments with circleci env subst

- src/scripts/run_tests.sh
Adds `eval` to environment variables containing commands to ensure they are interpreted correctly.
Bug when interpreting commands set by user.
Adds `eval` to ensure all characters are interpreted as expected.
> Fixes bug with `run_tests` command interpretation
